In [1]:
import numpy as np


In [7]:
arr1=np.random.randint(20,35,50)
arr2=arr1.flatten()
print(arr1)
print(arr2)
print(np.mean(arr2))
print(np.mean(arr2))


[21 22 24 28 26 33 22 34 23 22 20 28 20 28 22 21 27 27 24 31 30 26 28 32
 23 27 29 26 20 34 28 33 33 28 22 32 27 27 29 32 28 32 24 29 24 30 27 30
 33 22]
[21 22 24 28 26 33 22 34 23 22 20 28 20 28 22 21 27 27 24 31 30 26 28 32
 23 27 29 26 20 34 28 33 33 28 22 32 27 27 29 32 28 32 24 29 24 30 27 30
 33 22]
26.96


In [7]:
arr=np.array([19,1,28,10])
arr1=np.sort(arr)
print(arr1)
print(arr1[::-1])

[ 1 10 19 28]
[28 19 10  1]


In [10]:
arr=np.arange(1,19)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [15]:
arr=np.array([19,1,28,10])
arr1=np.sort(arr)
print(arr1)
for i in range(3):
    if arr[i] > arr[i+1]:
        arr[i]=arr[i+1]
print(arr)

[ 1 10 19 28]
[ 1  1 10 10]
